networks:
  arnelify-network:
    name: arnelify-network
    driver: bridge
    
services:
  cpp:
    container_name: cpp
    build:
      context: .
      dockerfile: cpp.dockerfile
    volumes:
      - ./pod:/var/www/cpp/pod
      - ./src:/var/www/cpp/src
    restart: unless-stopped
    networks:
      - arnelify-network
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    tty: true
  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_MASTER_PASS}
      - MYSQL_DATABASE=${MYSQL_MASTER_NAME}
      - TZ=Europe/Kiev
    volumes:
      - ./docker/mysql/volumes/:/var/lib/mysql/
    command: --default-authentication-plugin=caching_sha2_password
    restart: unless-stopped
    networks:
      - arnelify-network
    tty: true
  pma:
    container_name: pma
    image: phpmyadmin:latest
    restart: always
    environment:
      - PMA_HOST=mysql
      - PMA_ARBITRARY=1
    networks:
      - arnelify-network
    ports:
      - "8080:80"
    depends_on:
      - mysql
    tty: true