  cpp:
    container_name: cpp
    build:
      context: .
      dockerfile: cpp.dockerfile
    volumes:
      - ./pod:/var/www/cpp/pod
      - ./src:/var/www/cpp/src
    restart: unless-stopped
    networks:
      - arnelify-network
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    tty: true