networks:
  arnelify-network:
    name: arnelify-network
    driver: bridge
    
services:
  cpp:
    container_name: cpp
    build:
      context: .
      dockerfile: cpp.dockerfile
    volumes:
      - ./:/var/www/cpp
    restart: unless-stopped
    networks:
      - arnelify-network
    ports:
      - "3001:3001"
    tty: true